### ISSUE TITLE
Epic TypeScript support

### ISSUE THREAD

**Issue by qfox** [bem/bem-sdk#300]
Bring it to life!

- [ ] TSlint: https://github.com/agrarium/agrarium/pull/32/commits/c243107f121a1f2a4753666aa85074afa51ce1f5
- [ ] Pull some typings from https://github.com/agrarium/agrarium/blob/154eb7f4b938591396de9face3fafe804a09c215/packages/types/index.d.ts
- [ ] Rewrite containers to `ts`

**Comment by veged** [comment]
Fixed by #398 — все 22 пакета `@bem/sdk.*` мигрированы на TypeScript ESM. Каждый пакет публикует `dist/index.d.ts`, отдельные `@types/*` пакеты больше не нужны. См. также MIGRATION.md в репо.
